### ISSUE TITLE
out of space while building image

### ISSUE THREAD

**Issue by hvgazula** [hvgazula/build_docker#1]
@gaiborjosue Please see this https://github.com/hvgazula/build_docker/actions/runs/5695180979 and the docker file/folder is https://github.com/neuroneural/Vox2Cortex_fork/tree/main/docker

Please let me know how it goes on your end.

**Comment by hvgazula** [comment]
Looks like I'll have to do it on AWS now. 🤦‍♂️

**Comment by gaiborjosue** [comment]
Hello @hvgazula, can you please try this:

https://github.com/actions/runner-images/issues/2840#issuecomment-790492173

That should free some space.

**Comment by gaiborjosue** [comment]
@hvgazula I finished building Vox2Cortex docker image locally. It is around 26gb.

**Comment by hvgazula** [comment]
What about using GA with the suggestion you gave earlier?

**Comment by gaiborjosue** [comment]
I'll try it right now

**Comment by gaiborjosue** [comment]
@hvgazula It worked! It took 26mins, but it worked. 😅 I am going to create a PR with the updated workflow
