### ISSUE TITLE
Disable running workflows of outside Repos

### ISSUE THREAD

**Issue by gaiborjosue** [hvgazula/build_docker#5]
I think you should disable the actions for outside repos and only run workflows for actions within this repo. So that in each PR, the workflow does not run again in the user's repo as a check.

**Comment by hvgazula** [comment]
I am not sure I understand this.

**Comment by hvgazula** [comment]
never mind

**Comment by hvgazula** [comment]
It's okay. It's my own testbed. Tbh, I wasn't expecting any PRs here. :)

**Comment by gaiborjosue** [comment]
👍
